parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: ./tsconfig.json
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
plugins:
  - '@typescript-eslint'
env:
  node: true
  es6: true
rules:
  prettier/prettier:
    - error
    - semi: false
    - singleQuote: true